version: '3.9'

services:

  nest:
    container_name: nest
    image: node:17-alpine
    volumes:
      - ../nest/:/app
    working_dir: /app
    command: >
      sh -c "
        npm i -g @nestjs/cli &&
        npm install &&
        npm run start
      "

  next:
    container_name: next
    image: node:17-alpine
    volumes:
      - ../next/:/app
    working_dir: /app
    command: >
      sh -c "
        npm install &&
        npm run dev
      "

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/:/etc/mysql/conf.d/
