version: '3.9'

services:

    nest:
        container_name: nest
        image: node:17-alpine
        volumes:
            - ../nest/:/app
        working_dir: /app
        command: sh -c "npm install && npm run start"

    next:
        container_name: next
        image: node:17-alpine
        volumes:
            - ../next/:/app
        working_dir: /app
        command: sh -c "npm install && npm run build && npm run start"

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/:/etc/nginx/conf.d/
